#!/bin/bash

set -o errexit
set -o nounset

function cleanup_key() {
    local id="$1"; shift

    if [ -f "${TRANSCODE_INSTANCED_PATH}/${id}/keyinfo" ]; then
        local current="$( tail -n+2 "${TRANSCODE_INSTANCED_PATH}/${id}/keyinfo" | head -n1 )"
        find "${TRANSCODE_STREAM_PATH}/${id}" -name '*.key' ! -name "${current}" -type f -exec rm -f {} +
    else
        find "${TRANSCODE_STREAM_PATH}/${id}" -name '*.key' -type f -exec rm -f {} +
    fi
}

function generate_iv() {
    openssl rand -hex 16
}

function generate_key() {
    local filename="$1"; shift

    openssl rand 16 > "${filename}"
}

function generate_keyinfo() {
    local id="$1"; shift
    local uuid="$( openssl rand -hex 8 )"

    mkdir -p "${TRANSCODE_STREAM_PATH}/${id}"
    generate_key "${TRANSCODE_STREAM_PATH}/${id}/${uuid}.key"

    echo "${uuid}.key" > "${TRANSCODE_INSTANCED_PATH}/${id}/keyinfo"
    echo "${uuid}.key" >> "${TRANSCODE_INSTANCED_PATH}/${id}/keyinfo"
    echo "$( generate_iv )" >> "${TRANSCODE_INSTANCED_PATH}/${id}/keyinfo"
}

cleanup_key "$@"
generate_keyinfo "$@"
